### ISSUE TITLE
Delay acceleration so it starts after a certain distance was scrolled?

### ISSUE THREAD

**Issue by tobealive** [albertz/mouse-scroll-wheel-acceleration-userspace#6]
Hey I'm using your script for almost 2 years now. It really helps :)

I'm experiencing one downside when I want to do smaller step scrolls e.g. when scrolling through zoom steps or when scrolling through tabs in browsers (e.g. Vivaldi has a neat little alt+scroll feature that can be quite helpful with quicker tab switching). And in similar scenarios where detailed zoom steps are required. 

When scroll acceleration is activated, some of the Zoom steps, tabs etc. are skipped even when scrolling just a little. The issue would be solved if it was possible for the acceleration to kick in after a certain distance not right from the beginning.

Would you think about that and is it possible to implement such an option or make it the basic behavior?

**Comment by tobealive** [comment]
The thought of something like a timeout came to my mind

**Comment by albertz** [comment]
Hey, nice to hear that it is useful to you! I'm also using it myself all the time.

What you describe should already the case though. Every time the script recognizes a user scroll event, it stores the time stamp alongside. Based on the user scroll events and their timing, it estimates your current user scroll speed. And then it calculates given your settings how much it should accelerate, i.e. specifically it calculates a multiplicative factor `m` for the user scroll speed:
https://github.com/albertz/mouse-scroll-wheel-acceleration-userspace/blob/e64c413fa36650bd647180b2b869b0b82e0f2e8b/main.py#L84

When `m <= 1`, no acceleration is done.

Otherwise, it calculates the amount of additional scroll events it should generate, as:
```
scroll_ = user_vel * m - cur_vel
```
`cur_vel` is the current (possible already accelerated) scroll speed.
`user_vel` is the user scroll speed (any acceleration subtracted).

When you start `main.py` directly and give it `-v` or `-vv`, you will see some verbose statistics of this.
- You will see all the scroll events (with `-vv` only; `on scroll`, by user `gen False`, or the generated ones `gen True`).
- You will see when it accelerates (`accel multiplier`, `target vel`, `-> scroll X`).
 
If the generated scroll amount `X` is below 0.5, this will also not generate a scroll event.

So, to get back to your request: When you now scroll slowly, you should see in the verbose statistics that it will never generate any scroll events.

What are your settings? I use this on Linux:
```
2022-01-07 13:10:15,475 INFO: Loaded config /home/az/.config/mouse-scroll-wheel-accelerator/config.py
2022-01-07 13:10:15,475 INFO: Use config setting multiplier = 0.5
2022-01-07 13:10:15,475 INFO: Use config setting exp = 2
```

**Comment by tobealive** [comment]
Thanks for your reply! It's definitely a crucial feature. I switched from a Logitech Mouse with a free spin mouse technology to a vertical mouse with more of a classical scrolling wheel. Once you experience free-spin, it becomes painful without 😆. God bless the FOSS community that scripts like this exist. It is very close the freespin results now.  

Coming back to the issue:
I'm also on Linux and used the script with several distros since I discovered it. The current settings are `--exp 0.8 --multiplier 1.5 `. From the little testing I've done the issue is persistent with other settings.

But I see now that it's probably not the issue I thought it is in my first message.

Maybe it's more about the handling of inputs, because having the accel enabled in a significant number of cases "single-scrolls" (scrolling one ratchet) are not recognized / executed. Then scrolling a second ratchet, two scroll steps are executed. I can just pretend to be an expert which wouldn't lead to a result, you can probably tell better than me what the reason is.

If you have the time and want to get your hands on a scenario with a problem like this: If you have Vivaldi installed: Open multiple tabs, somewhere in the browser window alt+scroll and see how tab switching behaves. I think this could also be tested in other chromium based browsers. Then just hover the tabs and scroll without a modifier key.

**Comment by tobealive** [comment]
Thinking of a possible solution: would it be possible to add that the acceleration is only used with a certain key / key-combination? Or the other way around that it temporarily deactivates when holding a certain key/s and scrolling.

**Comment by albertz** [comment]
When you wait long enough between each single scroll (and each single scroll is little enough), the acceleration should never kick in because the user scroll speed is too slow. The acceleration formula is:
```
def _acceleration_scheme_get_scroll_multiplier(self, abs_vel: float) -> Union[int, float]:
  if abs_vel <= 1:
    return 1

  # Exponential scheme.
  m = abs_vel ** self.accel_factor_exp
  return m * self.accel_factor
```
This returns the multiplicator for the user scroll speed (`abs_vel` here). So returning a factor <= 1 would not increase it.

`accel_factor` is the `multiplier` setting.
`accel_factor_exp` is the `exp` setting.

Maybe what you want is that this acceleration scheme is just different? Maybe you can suggest some formula to what it should be?

**Comment by albertz** [comment]
> Thinking of a possible solution: would it be possible to add that the acceleration is only used with a certain key / key-combination? Or the other way around that it temporarily deactivates when holding a certain key/s and scrolling.

This is a good idea but this would be a somewhat orthogonal idea. So maybe let's discuss this in a separate issue.

What you raised here in this issue (the acceleration scheme maybe being suboptimal) is also valid.

**Comment by albertz** [comment]
When your `multiplier > 1`, the acceleration would always kick in once you reach this minimal scroll speed. That's maybe the effect you describe.

**Comment by tobealive** [comment]
Thanks for the info. It's nice to get some context to follow a little along how it works. Still having some trouble understanding why some single scrolls won't execute. 

I hadn't had the chance to get into programming that much. I would like to suggest something, but I wouldn't actually know what I am doing.

**Comment by tobealive** [comment]
> en your `multiplier > 1`, the acceleration would always kick in once you reach this minimal scroll speed. That's maybe the effect you describe.

Oh, nice! Based on that, I tweaked the settings again. Now it's closer to the desired result.
`--exp 1 --multiplier .5` 
Does the job know quiet well.

**Comment by albertz** [comment]
Ah I missed your edit. Good to know that this was resolved.
